### ISSUE TITLE
i was just wondering whenever i am changing locale by setlocale method why the locale.ready event is not trigerring which is written inside directive. 

### ISSUE THREAD

**Issue by vivdkool** [doshprompt/angular-localization#23]
link: function(scope, element){
			scope.labels = {};
			locale.ready('radar').then(function () {
			    scope.labels.PLACE = locale.getString('radar.PLACE');
			    scope.labels.PRICE = locale.getString('radar.PRICE');
			    scope.labels.PROMO = locale.getString('radar.PROMO');
			    scope.labels.OPPORTUNITY = locale.getString('radar.OPPORTUNITY');
			    scope.labels.SALESDOLLARS = locale.getString('radar.SALESDOLLARS');
			});
			
scope.$watch('labels.PLACE', function () {
			    if (scope.labels.PLACE!=undefined)
			        drawRadar();
			})

**Comment by doshprompt** [comment]
Hi, this is expected. The locale.ready returns a promise, and the promise is resolved once the locale service has loaded the file requested in the language set.

When the language is changed a new promise is created to handle the new file load, so your locale.ready won't re-trigger since it is hooked to the old promise. There is no way to reset a promise so you will have to attach a new locale.ready handler for that.

You will have to put the locale.ready inside a listener for the locale changed event so that you can programmatically re-capture every time the language is changed.

```js
angular.module('my.module', ['ngLocalize'])
    .controller('MyCtrl', function(locale, localeEvents) {
        $scope.$on(localeEvents.localeChanges, function () {
            locale.ready('common').then(function() {
                $scope.strings.yes = locale.getString('common.yes');
            });
        });
    });
```

**Comment by doshprompt** [comment]
https://gist.github.com/revolunet/6771456
