### ISSUE TITLE
Protractor testing

### ISSUE THREAD

**Issue by MichalMazurek** [doshprompt/angular-localization#25]
Hi,

Did you guys notice that when you run the tests from protractor, the localisation is not run?
E.g.

    expect($(".more-button span[data-i18n='navbar.more']").getText()).toNotBe("")

This fails unfortunately, do I need to add something in beforeEach to wait for the localisation? I think that might be the problem.

Thanks for the great job :)
Michal

**Comment by jderrough** [comment]
Hi Michal,

You can take a look at how things are done in https://github.com/doshprompt/angular-localization/blob/master/tests/unit/directiveSpec.js

Cheers,
Jonathan

**Comment by brycecr** [comment]
On protractor testing, it appears to be broken in travis currently. Don't know much about protractor myself, but that seems like am impediment to code contributions going forward so should be fairly high priority. 

I.e. I doubt master passes travis because protractor is failing creation. See example logs here:
https://travis-ci.org/doshprompt/angular-localization/builds/51906401

**Comment by doshprompt** [comment]
@brycecr thanks for pointing that out, I have found the root cause of the issue is a fault with protractor + phantomjs (selenium, phantom most likely are to be blamed) and an issue is currently open on protractor

https://github.com/angular/protractor/issues/1512

I have disabled e2e testing altogether as it isn't very meaningful right now, will re-enable once the issue is fixed and/or we have some actual test cases, then we may run the suite in chrome etc.
