### ISSUE TITLE
language choose and persist

### ISSUE THREAD

**Issue by unruledboy** [doshprompt/angular-localization#73]
Firstly, I have to say this is a really awesome project, love it!

a few suggestions about language choose and persist. 

1. it would be great to document the implementation of the real world usage, like the one you did at the top right hand side in http://doshprompt.github.io/angular-localization/   I spent a while to figure out how to replicate that in my project.

2. you did not mention developer needs to inject ngCookies in module and use $cookieStore service in the controller, and, the $cookieStore is deprecated: https://docs.angularjs.org/api/ngCookies/service/$cookieStore  , and because the cookie is session based, after user closes the browser and open again, it can't retrieve the last chosen language.

3. the documentation of Custom Configuration is kinda misleading, for example, defaultLocale: 'languages', it should a specific language, right?

**Comment by bretkikehara** [comment]
1. Sorry to hear that it took a while to figure out! @doshprompt had put a together a [minimum viable demo app](https://github.com/doshprompt/angular-localization/tree/master/app). IMO the demo app could probably use some love to make it simpler to understand, but it works.

2. The [quickstart guide](https://github.com/angular/angular.js/blob/master/src/ngCookies/cookieStore.js#L4) mentions that cookies are part of the dependencies. But it seems like the main project page doesn't mention cookies at all. Good catch.

Your right about the deprecation of $cookieStore. It was deprecated in angular v1.4.x in favor or $cookies. Since angular-localization supports angular v1.2.x, we must rely on $cookieStore for backwards compatibility. In angular v1.4.x, [$cookieStore actually relies on the $cookie service](https://github.com/angular/angular.js/blob/v1.4.x/src/ngCookies/cookieStore.js). =]

3. Seems to be an error in the main project page. Good Catch.

**Comment by unruledboy** [comment]
thanks for the reply, mate.
