### ISSUE TITLE
Bower package dependency is causing angular version to cascade update

### ISSUE THREAD

**Issue by jcachat** [doshprompt/angular-localization#97]
In "bower.json", you are specifying the versions of your dependencies as ">=1.2 < 2".  This is causing bower to download the most recent version of those packages.  "angular-sanitize" has been upgraded (as of now, to version 1.5.8) which requires Angular 1.5.8.  So this is causing my entire project to suddenly upgrade Angular itself to 1.5.8 when I am expecting it to be 1.4.7!

And because "sanitize" is a dependency and is only downloaded when "localization" is updated, we now have 3 developers still running Angular 1.4.7 and one that mysteriously got updated to 1.5.8!

I have been able to prevent this from happening by adding "angular-sanitize" to my own bower.json file and specifying it's version as 1.4.7.  But could you please set specific versions so that we don't have unintended updates to other packages?

**Comment by bretkikehara** [comment]
I would suggest it is good practice to define all dependencies inside your package.json even the child dependencies so there is no confusion on how bower should resolve. 

Say we set angular to be 1.4. If I am not mistaken, the problem with setting a static version in our library is then anyone with angular 1.5 or greater will have resolution conflicts. IMO, a library should be loose on its child dependencies so that each app can define its own dependency versions without much friction.

**Comment by jcachat** [comment]
Yes, I agree.  I can see how that could just cause other dependency issues.  Ideally, it would probably be handled better by bower (to do a better job of picking dependent packages with a range of versions to avoid upgrading a package I have included).

We have already gone through the other packages we use and made sure we're including any necessary dependencies.  So it's all working fine now.  We'll just need to be aware of this in the future.

Thanks for your input.  Closing the issue.
